" ~/.vimrc
"
" @author Augusto Pascutti

" Pathogen
execute pathogen#infect()
set nocompatible
filetype plugin indent on

" Map keys
map <C-e> :PHPClassExplorer<CR>
map <C-n> :NERDTreeToggle<CR>

" Globals
"
set hlsearch
set noswapfile
filetype indent plugin on
syn on
set sm              " show matching brackets
set ts=4            " tab stop
set et              " expand tabs
retab               " converts existing tabs
set ruler           " shows ruler
set laststatus=1   " lines of status
set nosmartindent   "
set visualbell      " visual bell
set sw=4            " shift width (>)
set wildmode=longest,list:full
set guioptions=aAce
set cursorline      " highlugh current line
set number          " show line numbers (gutter-like)
set backspace=indent,eol,start
" For the lazy
"
autocmd BufWritePre * :%s/\s\+$//e " Removes whitespace on write. (Because I am tired of feeling a badass doing that)

" Color scheme options
"
set bg=dark
set t_Co=256
colorscheme solarized
"let g:airline_powerline_fonts = 0 " vim-airline use of patched fonts.
"let g:airline_left_sep = '|'
"let g:airline_right_sep = '|'
