" ~/.vimrc
"
" @author Augusto Pascutti

" Pathogen
call pathogen#infect()

" Globals
"
set hlsearch
set noswapfile
filetype indent plugin on
syn on
set sm              " show matching brackets
set ts=4            " tab stop
set et              " expand tabs
retab               " converts existing tabs
set ruler           " shows ruler
set laststatus=1   " lines of status
set nosmartindent   "
set visualbell      " visual bell
set sw=4            " shift width (>)
set wildmode=longest,list:full
set guioptions=aAce
set cursorline      " highlugh current line
set number          " show line numbers (gutter-like)

" For the lazy
"
autocmd BufWritePre * :%s/\s\+$//e " Removes whitespace on write. (Because I am tired of feeling a badass doing that)

" Color scheme options
"
set bg=light
"set t_Co=256
colorscheme solarized
let g:airline_powerline_fonts = 1 " vim-airline use of patched fonts.

" Custom syntaxes


" Map keys
map <C-e> :PHPClassExplorer<CR>
map <C-q> :q!<CR>
map <C-s> :w<CR>
map <C-T> :NERDTreeTabsToggle<CR>
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
