" ~/.vimrc
"
" @author Augusto Pascutti

" Pathogen
"
execute pathogen#infect()
set nocompatible
filetype plugin indent on

" Map keys
map <C-n> :NERDTreeToggle<CR>
nnoremap <leader>s :grep! "\b<C-R><C-W>\b"<CR>:copen<CR>

" Globals
"
set incsearch
set hlsearch
set exrc
syn on
set sm              " show matching brackets
set ts=4            " tab stop
set et              " expand tabs
retab               " converts existing tabs
set ruler           " shows ruler
set laststatus=2   " lines of status
set nosmartindent   "
set visualbell      " visual bell
set sw=4            " shift width (>)
set wildmode=longest,list:full
set guioptions=aAce
set cursorline      " highlugh current line
set number          " show line numbers (gutter-like)
set backspace=indent,eol,start

" Color scheme options
"
set background=light
set t_Co=256
colorscheme papercolor

" Cosmetic plugin configuration
"
let g:airline_powerline_fonts = 1
let g:gitgutter_sign_column_always = 1
let g:gitgutter_enabled = 1
let g:gitgutter_signs = 1

" The silver searcher
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
    let g:ctrlp_use_caching = 0
endif

" Use Github Flavoured markdown by default on markdown files
augroup markdown
    au!
    au BufNewFile,BufRead *.md,*.markdown setlocal filetype=ghmarkdown
augroup END
